=== liuwenjiexx/LWJ.FSM/resources/lwj.fsm.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="urn:schema-lwj:fsm"
           xmlns="urn:schema-lwj:fsm"
           xmlns:mtns="urn:schema-lwj:fsm"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">


  <xs:element name="fsm"  >
    <xs:annotation>
      <xs:documentation>
        Finite State Machine(FSM), fsm root node
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="transitionalStateType">
          <xs:attribute name="name"   />
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>

    <xs:unique name="rootStateNames">
      <xs:selector xpath="mtns:state|mtns:parallel|mtns:final"/>
      <xs:field xpath="@name"/>
    </xs:unique>
  </xs:element>


  <!-- state -->

  <xs:element name="transitionalTarget"  abstract="true">

  </xs:element>

  <xs:element name="enterableState"   abstract="true" substitutionGroup="transitionalTarget" />

  <xs:element name="transitionalState"  abstract="true"  substitutionGroup="enterableState">
  </xs:element>

  <xs:complexType name="transitionalTargetType">
    <xs:sequence>
      <xs:element ref="params" minOccurs="0"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="onEntry"/>
        <xs:element ref="onExit"/>
        <xs:group ref="actionsGroup"/>
      </xs:choice>
    </xs:sequence>

  </xs:complexType>

  <xs:complexType name="enterableStateType">
    <xs:sequence>
      <xs:element ref="params" minOccurs="0"/>
      <xs:element ref="entry" minOccurs="0" maxOccurs="1" />
      <xs:element ref="exit" minOccurs="0" maxOccurs="1"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="enterableState"/>
        <xs:element ref="onEntry"/>
        <xs:element ref="onExit"/>
        <xs:group ref="actionsGroup"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name"  use="required" >
      <xs:annotation>
        <xs:documentation>
          state name
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="transitionalStateType">

    <xs:sequence>
      <xs:element ref="params" minOccurs="0"/>
      <xs:element ref="transition" minOccurs="0" maxOccurs="unbounded"/>
      <!--<xs:element ref="onInitial" minOccurs="0" maxOccurs="1"/>-->
      <xs:element ref="entry" minOccurs="0" maxOccurs="1" />
      <xs:element ref="exit" minOccurs="0" maxOccurs="1"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="enterableState"/>
        <xs:element ref="onEntry"/>
        <xs:element ref="onExit"/>
        <xs:group ref="actionsGroup"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name"  use="required" >
      <xs:annotation>
        <xs:documentation>
          state name
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="initial" type="state_id_type" />

  </xs:complexType>


  <xs:simpleType name="state_id_type">
    <xs:restriction base="xs:string">
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="stateType">
    <xs:sequence>
    </xs:sequence>
  </xs:complexType>

  <!--state-->

  <xs:element name="state"   substitutionGroup="transitionalState">
    <xs:annotation>
      <xs:documentation>
        state
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="transitionalStateType">
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
    <xs:unique name="stateNames">
      <xs:selector xpath="mtns:state|mtns:parallel|mtns:final"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:key name="paramName">
      <xs:selector xpath="params/param"/>
      <xs:field xpath="@name"/>
    </xs:key>
  </xs:element>


  <xs:element name="parallel" substitutionGroup="transitionalState">
    <xs:annotation>
      <xs:documentation>
        parallel state
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="transitionalStateType">
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
    <xs:unique name="parallelStateNames">
      <xs:selector xpath="mtns:state|mtns:parallel|mtns:final"/>
      <xs:field xpath="@name"/>
    </xs:unique>

  </xs:element>

  <!-- final state-->

  <xs:element name="final" substitutionGroup="enterableState">
    <xs:annotation>
      <xs:documentation>
        final state
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="enterableStateType">
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <!--entry state-->

  <xs:element name="entry" substitutionGroup="transitionalTarget">
    <xs:annotation>
      <xs:documentation>
        entry state
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="params" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="transition" minOccurs="0" maxOccurs="unbounded"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="onEntry"/>
          <xs:element ref="onExit"/>
          <xs:group ref="actionsGroup"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--exit state-->

  <xs:element name="exit" substitutionGroup="transitionalTarget">
    <xs:annotation>
      <xs:documentation>
        exit state
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="transitionalTargetType">
          <xs:sequence>
            <xs:group ref="actionsGroup" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>


  <xs:element name="params">
    <xs:annotation>
      <xs:documentation>
        parameters
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="param" >
    <xs:annotation>
      <xs:documentation>
        parameter
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="exprParentType">
          <xs:attribute name="type" use="required" />
          <xs:attribute name="name" use="required"  />
          <xs:attribute name="value" />
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>


  <xs:element name="cond"  type="exprParentType">
    <xs:annotation>
      <xs:documentation>
        bool value expression
      </xs:documentation>
    </xs:annotation>
  </xs:element>

  <!-- executable -->

  <xs:element name="transition">
    <xs:annotation>
      <xs:documentation>
        state transition
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cond" minOccurs="0"/>
        <xs:group ref="actionsGroup" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="event">
        <xs:annotation>
          <xs:documentation>
            match event
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="target" type="state_id_type">
        <xs:annotation>
          <xs:documentation>
            transition next state
          </xs:documentation>
        </xs:annotation>

      </xs:attribute>

    </xs:complexType>

  </xs:element>


  <xs:element name="onEntry">
    <xs:annotation>
      <xs:documentation>
        state entry event
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="actionsGroup" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="onExit">
    <xs:annotation>
      <xs:documentation>
        state exit event
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="actionsGroup" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="onUpdate">
    <xs:annotation>
      <xs:documentation>
        state update event
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="actionsGroup" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <!-- action -->

  <xs:element name="action" abstract="true"/>

  <xs:complexType name="actionType" >
  </xs:complexType>

  <xs:complexType name="actionsContainerType">
    <xs:sequence>
      <xs:group ref="actionsGroup" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:group name="actionsGroup">
    <xs:choice>
      <xs:element ref="action"/>
      <xs:any namespace="##other"/>
    </xs:choice>
  </xs:group>

  <xs:element name="expr"  type="exprsContainerType"  substitutionGroup="action">
    <xs:annotation>
      <xs:documentation>
        ExpressionAction, execute expression
      </xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="log" substitutionGroup="action">
    <xs:annotation>
      <xs:documentation>
        LogAction, log message
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="exprsContainerType">
          <xs:annotation>
            <xs:documentation>
              arguments expression
            </xs:documentation>
          </xs:annotation>
          <xs:attribute name="type" >
            <xs:annotation>
              <xs:documentation>
                log type
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="msg" >
            <xs:annotation>
              <xs:documentation>
                log message
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="format" >
            <xs:annotation>
              <xs:documentation>
                message format
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="raise" substitutionGroup="action">
    <xs:annotation>
      <xs:documentation>
        RaiseAction, raise event
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="actionType">
          <xs:sequence>
            <xs:element name="data"  minOccurs="0" maxOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:group ref="exprGroup" minOccurs="0" maxOccurs="1" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="event" />
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="cancel"  substitutionGroup="action">
    <xs:annotation>
      <xs:documentation>
        CancelAction, cancel event
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="actionType">
          <xs:attribute name="event" />
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="if"  substitutionGroup="action">
    <xs:annotation>
      <xs:documentation>
        IfAction
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="actionType">
          <xs:sequence>
            <xs:element ref="cond" />
            <xs:element name="then" type="actionsContainerType" />
            <xs:element name="elseIf" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element ref="cond" />
                  <xs:element name="then" type="actionsContainerType" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="else" type="actionsContainerType" minOccurs="0" maxOccurs="1">
            </xs:element>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="foreach" substitutionGroup="action">
    <xs:annotation>
      <xs:documentation>
        ForeachAction
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="actionType">
          <xs:sequence>
            <xs:element name="items" type="exprParentType">
              <xs:annotation>
                <xs:documentation>
                  items expression
                </xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:group ref="actionsGroup" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
          <xs:attribute name="item"/>
          <xs:attribute name="index"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="assign"  substitutionGroup="action">
    <xs:annotation>
      <xs:documentation>
        AssignAction
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="actionType">
          <xs:group ref="exprGroup" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>
                parameter value
              </xs:documentation>
            </xs:annotation>
          </xs:group>
          <xs:attribute name="name"  use="required">
            <xs:annotation>
              <xs:documentation>
                parameter name
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="value">
            <xs:annotation>
              <xs:documentation>
                parameter value
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>

  </xs:element>

  <!--expression-->

  <xs:group name="exprGroup">
    <xs:sequence>
      <xs:any namespace="urn:schema-lwj:expression" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="exprParentType">
    <xs:annotation>
      <xs:documentation>
        A subexpression
      </xs:documentation>
    </xs:annotation>
    <xs:group ref="exprGroup" minOccurs="0" maxOccurs="1" />
  </xs:complexType>

  <xs:complexType name="exprsContainerType">
    <xs:annotation>
      <xs:documentation>
        Multiple sub-expressions
      </xs:documentation>
    </xs:annotation>
    <xs:group ref="exprGroup" minOccurs="0" maxOccurs="unbounded"/>
  </xs:complexType>

</xs:schema>

=== liuwenjiexx/LWJ.FSM/test/LWJ.FSM.Xml.Test/xml/actions/raise.xml
<?xml version="1.0" encoding="utf-8" ?>
<fsm xmlns="urn:schema-lwj:fsm"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:schema-lwj:fsm ../../../../resources/lwj.fsm.xsd"
     initial="s1">
  <state name="s1">
    <transition target="s2" event="to.s2" />
    <onEntry>
      <raise event="to.s2"/>
    </onEntry>
  </state>
  <state name="s2">
    <transition target="s3" event="to.s3"/>
    <onEntry>
      <raise event="to.s3"/>
    </onEntry>
  </state>
  <state name="s3" />
</fsm>

=== liuwenjiexx/LWJ.FSM/test/LWJ.FSM.Xml.Test/xml/transition_event_cond.xml
<?xml version="1.0" encoding="utf-8" ?>
<fsm xmlns="urn:schema-lwj:fsm"
     xmlns:x="urn:schema-lwj:expression"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:schema-lwj:fsm ../../../resources/lwj.fsm.xsd
      urn:schema-lwj:expression ../../../resources/lwj.expr.xsd"
    initial="s1">
  <params>
    <param type="bool" name="a" value="false"/>
  </params>
  <state name="s1">
    <transition target="s2" event="to.s2">
      <cond>
        <x:var>a</x:var>
      </cond>
    </transition>
  </state>
  <state name="s2"></state>
</fsm>

=== liuwenjiexx/LWJ.FSM/test/LWJ.FSM.Xml.Test/xml/entry_trace.xml
<?xml version="1.0" encoding="utf-8" ?>
<fsm xmlns="urn:schema-lwj:fsm"
     xmlns:x="urn:schema-lwj:expression"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:schema-lwj:fsm ../../../resources/lwj.fsm.xsd
      urn:schema-lwj:expression ../../../resources/lwj.expr.xsd"
   >
  <entry>
    <transition target="s1">
      <log msg="entry.transition"/>
    </transition>
    <onEntry>
      <log msg="entry.onentry" />
    </onEntry>
    <onExit>
      <log msg="entry.onexit" />
    </onExit>
    <log msg="entry.update"/>
  </entry>
  <exit>
    <onEntry>
      <log msg="exit.onentry" />
    </onEntry>
    <onExit>
      <log msg="exit.onexit" />
    </onExit>
  </exit>
  <state name="s1">
    <transition target="state.exit" event="to.exit"/>
    <entry>
      <log msg="s1.entry.update"/>
    </entry>
    <onEntry>
      <log msg="s1.entry.onentry" />
    </onEntry>
    <onExit>
      <log msg="s1.entry.onexit" />
    </onExit>
    <log msg="s1.update"/>
  </state>   
  <log msg="update"/>  
</fsm>

=== liuwenjiexx/LWJ.FSM/test/LWJ.FSM.Xml.Test/xml/params.xml
<?xml version="1.0" encoding="utf-8" ?>
<fsm xmlns="urn:schema-lwj:fsm"
     xmlns:x="urn:schema-lwj:expression"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:schema-lwj:fsm ../../../resources/lwj.fsm.xsd
      urn:schema-lwj:expression ../../../resources/lwj.expr.xsd"
    initial="s1">
  <params>
    <param type="int32" name="i_0"  />
    <param type="int64" name="l_0"  />
    <param type="int32" name="i_1" value="1"  />
    <param type="int32" name="i_2"  >
      <x:int>2</x:int>
    </param>

    <param type="float32" name="f_0"  />
    <param type="float64" name="d_0"  />
    <param type="float32" name="f_01" value="0.1" />
    <param type="float32" name="f_02"  >
      <x:float>0.2</x:float>    
  </param>

    <param type="bool" name="b_false" />
    <param type="bool" name="b_true" value="true" />
    <param type="bool" name="b_false2" value="false" />
    <param type="bool" name="b_true2" >
      <x:bool>true</x:bool>
    </param>

    <param type="string" name="s_null"   />
    <param type="string" name="s_abc" value="abc"  />
    <param type="string" name="s_123"   >
      <x:string>123</x:string>    
  </param>

    <param type="type" name="t_null"   />
    <param type="type" name="t_string"  value="System.String"/>
    <param type="type" name="t_int">
      <x:type>System.Int32</x:type>    
  </param>

    <param type="datetime" name="datetime_value"  value="2017-01-02T03:04:05"/>
    <param type="datetime" name="datetime_expr">
      <x:datetime>2017-01-02T03:04:05</x:datetime>
    </param>

  </params>
  <state name="s1">
    <params>
      <param type="int32" name="ref_i_1">
        <x:var>i_1</x:var>      
    </param>
    </params>
  </state>
</fsm>

=== liuwenjiexx/LWJ.FSM/test/LWJ.FSM.Xml.Test/xml/actions/assign.xml
<?xml version="1.0" encoding="utf-8" ?>
<fsm xmlns="urn:schema-lwj:fsm"
     xmlns:x="urn:schema-lwj:expression"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:schema-lwj:fsm ../../../../resources/lwj.fsm.xsd
         urn:schema-lwj:expression ../../../../resources/lwj.expr.xsd"
     initial="s1">
  <params>
    <param name="int32ByValue"  type="int32"/>
    <param name="stringByExpr"  type="string"/>
  </params>
  <state name="s1">
    <onEntry>
      <assign name="int32ByValue" value="1"></assign>
      <assign name="stringByExpr">
        <x:string>Hello World</x:string>
      </assign>
    </onEntry>
  </state>
</fsm>

=== liuwenjiexx/LWJ.FSM/test/LWJ.FSM.Xml.Test/xml/transition_trace2.xml
<?xml version="1.0" encoding="utf-8" ?>
<fsm  xmlns="urn:schema-lwj:fsm"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:x="urn:schema-lwj:expression"
      xsi:schemaLocation="urn:schema-lwj:fsm ../../../resources/lwj.fsm.xsd 
      urn:schema-lwj:expression ../../../resources/lwj.expr.xsd"
    name="root" initial="s1" >
  <params>
    <param type="int32" name="n" value="2"/>
    <param type="string" name="trace"/>
  </params>
  <state name="s1">
    <transition target="s2">
      <cond>
        <x:geq>
          <x:postDecrement>
            <x:var>n</x:var>
          </x:postDecrement>
          <x:int>0</x:int>
        </x:geq>      
    </cond>
      <log msg="s1.transition"/>
    </transition>
    <onEntry>
      <log msg="s1.entry"/>
    </onEntry>
    <onExit>
      <log msg="s1.exit"/>
    </onExit>
  </state>
  <state name="s2">
    <transition target="s1">
      <log msg="s2.transition"/>
    </transition>
    <onEntry>
      <log msg="s2.entry"/>
    </onEntry>
    <onExit>
      <log msg="s2.exit"/>
    </onExit>
  </state>
</fsm>

=== liuwenjiexx/LWJ.FSM/test/LWJ.FSM.Xml.Test/xml/parallel.xml
<?xml version="1.0" encoding="utf-8" ?>
<fsm xmlns="urn:schema-lwj:fsm"
     xmlns:x="urn:schema-lwj:expression"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:schema-lwj:fsm ../../../resources/lwj.fsm.xsd
      urn:schema-lwj:expression ../../../resources/lwj.expr.xsd"
     initial="s1"
   >
  <parallel name="s1">
    <transition target="s2" event="to.s2" />
    <onEntry>
      <log msg="s1.entry"/>
    </onEntry>
    <onExit>
      <log msg="s1.exit"/>
    </onExit>
    <state name="s11">
      <onEntry>
        <log msg="s11.entry"/>
      </onEntry>
      <onExit>
        <log msg="s11.exit"/>
      </onExit>
      <log msg="s11.update" />
    </state>
    <state name="s12">
      <onEntry>
        <log msg="s12.entry"/>
      </onEntry>
      <onExit>
        <log msg="s12.exit"/>
      </onExit>
      <log msg="s12.update"/>
    </state>
  </parallel>
  <state name="s2">
    <onEntry>
      <log msg="s2.entry"/>
    </onEntry>
    <onExit>
      <log msg="s2.exit"/>
    </onExit>
  </state>
</fsm>

=== liuwenjiexx/LWJ.FSM/test/LWJ.FSM.Xml.Test/xml/transition_trace.xml
<?xml version="1.0" encoding="utf-8" ?>
<fsm xmlns="urn:schema-lwj:fsm"
     xmlns:x="urn:schema-lwj:expression"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:schema-lwj:fsm ../../../resources/lwj.fsm.xsd
      urn:schema-lwj:expression ../../../resources/lwj.expr.xsd"
    name="root" initial="s1" >
  <state name="s1">
    
    <transition target="s2">
      <log msg="s1.transition" />      
    </transition>
    <onEntry>
      <log msg="s1.onEntry"/>
    </onEntry>
    <onExit>
      <log msg="s1.onExit"/>
    </onExit> 
  </state>
  <state name="s2">
    <transition target="s3">
      <log msg="s2.transition"/>
    </transition>
    <onEntry>
      <log msg="s2.onEntry"/>
    </onEntry>
    <onExit>
      <log msg="s2.onExit"/>
    </onExit>
  </state>
  <state name="s3">
    <onEntry>
      <log msg="s3.onEntry"/>
    </onEntry>
  </state>
</fsm>
